module.exports = {
    BOOKS_LIST: 'BOOKS_LIST',
    BOOKS_ADD: 'BOOKS_ADD',
    BOOKS_VIEW: 'BOOKS_VIEW',
    BOOKS_EDIT: 'BOOKS_EDIT',

    MESSAGE_SHOW: 'MESSAGE_SHOW',
    MESSAGE_DISMISS: 'MESSAGE_DISMISS',

    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',
}