module.exports = {
    BOOKS_LIST: 'BOOKS_LIST',
    BOOKS_ADD: 'BOOKS_ADD',
    BOOKS_VIEW: 'BOOKS_VIEW',
    BOOKS_EDIT: 'BOOKS_EDIT',

    MESSAGE_SHOW: 'MESSAGE_SHOW',
    MESSAGE_DISMISS: 'MESSAGE_DISMISS',

    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_LOGOUT: 'AUTH_LOGOUT',
    AUTH_CHECK: 'AUTH_CHECK'
}